providers = ['php', 'node']

[phases.build]
cmds = [
    'php artisan config:clear',
    'npm ci',
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force --no-interaction 2>&1 | grep -v "Nothing to migrate" || true; php artisan db:seed --force --no-interaction 2>&1 || true; exec nginx -c /assets/nginx.template.conf -g "daemon off;"'